### ISSUE TITLE
Did this fit?

### ISSUE THREAD

**Issue by DeadlySurgeon** [rallekralle11/Genna#1]
I figured I would leave this question here. Did you get it ordered, and did it fit well in your socket?

**Comment by rallekralle11** [comment]
It did fit nicely and made good contact, but it didn't work anyway. It seems the mega32U4 can't have the arduino bootloader written to it without any external oscillator. I'll probably redesign it sooner or later.

**Comment by DeadlySurgeon** [comment]
For my uses that'll probably be fine, but there should be some slim, discrete crystals. 

Either way, thanks for the reply!
